### ISSUE TITLE
Idea: A bot to run pre-commit and commit formatted code

### ISSUE THREAD

**Issue by sloria** [pre-commit/pre-commit.com#211]
It would be great to have a GitHub bot that could execute `pre-commit run ...` on a PR then add a commit to the PR with the formatting changes, if there are any.

This would act as a last resort, ensuring that both maintainers and contributors don't need to care about formatting code.

Does this exist? If not, is there any interest in collaborating on something like this?

## Prior discussions

* This same idea was suggested for prettier it was never implemented AFAICT: https://github.com/prettier/prettier/issues/238
* [This project](https://github.com/Mariatta/black_out) runs `black` and adds a commit. I suggested supporting pre-commit: https://github.com/Mariatta/black_out/issues/47

**Comment by sloria** [comment]
> Seems like a fine idea -- though I don't have the slightest idea on where to host such a thing however

The Probot docs have deployment instructions for Glitch, Heroku, Now, GH Actions, AWS Lambda, and Google Cloud Functions: https://probot.github.io/docs/deployment .

**Comment by sloria** [comment]
I wonder if this makes more sense as a GitHub Action. There's already actions implemented for a number of linters and formatters: https://github.com/bltavares/actions

**Comment by asottile** [comment]
I really really really want to set up a github action but I haven't been whitelisted into the beta yet :'(

**Comment by sloria** [comment]
The Restyled project (https://restyled.io/) uses GitHub actions to run formatters against PRs. I've suggested adding pre-commit support: https://github.com/restyled-io/restylers/issues/29

**Comment by Pierre-Sassoulas** [comment]
This Github action would would save so much time. I found [this existing action](https://github.com/ad-m/github-push-action) that look like a very close match. Maybe just adding ``pre-commit run --all-files`` would work:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        pre-commit run --all-files
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
 ```
