### ISSUE TITLE
what is the base directory for "log_file" output #1553

### ISSUE THREAD

**Issue by drjasonharrison** [pre-commit/pre-commit.com#375]
Originally reported as https://github.com/pre-commit/pre-commit/issues/1553

I'm running pytest using the following definition:

```
-   repo: local
    hooks:
    -   id: simple-pytest
        description: run pytest
        name: simple-pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [push]
        log_file: pytest.log
```
and I see pre-commit list pytest during the git push after I make a change to a .py source file and git add and git commit. But I cannot find a pytest.log file anywhere.

When I run pytest manually:
```
pytest > manual-pytest.log
```
The manual-pytest.log file is created in the current working directory.

This is on Ubuntu 18.04.4, with python 3.6.9, pytest 5.4.3

Conclusion: pytest is not failing -- that is why log file is created.
