### ISSUE TITLE
Version in docs is out of date

### ISSUE THREAD

**Issue by andrewasheridan** [pre-commit/pre-commit.com#806]
In [`sections/install.md`](https://github.com/pre-commit/pre-commit.com/blob/80c623d8f685a9162ff96d139747073aff61ccca/sections/install.md) the section named "Add a pre-commit configuration" shows this at the start of the sample config file:

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
```

That version, `2.3.0` is out of date. Should it be updated to the current `4.4.0`?
