### ISSUE TITLE
pre-commit ci incorrectly reports an error with the walrus operator (python 3.11)

### ISSUE THREAD

**Issue by kratsg** [pre-commit/pre-commit.com#841]
I'm honestly not quite sure whether this is an issue with mypy or with pre-commit ci. Particularly because I used `pyenv` to pull down 3.11 and tried to reproduce this locally (and could not).

Here's the run: https://results.pre-commit.ci/run/github/424389185/1686788394.g_pqatOXQ4aoIRlHLLCEOg

and this seems to be complaining about the line in here: https://github.com/executablebooks/markdown-it-py/blob/master/markdown_it/common/utils.py#LL106C1-L108C1

This occurred by pulling down `rich` as a `mypy` dependency in my `.pre-commit-config.yaml`, e.g. specifically

```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        files: src
        args: []
        additional_dependencies:
          ["types-Jinja2", "typer", "importlib_resources", "rich"]
```

Removing `rich` and telling `mypy` to ignore imports is a workaround I'm using for now, but I'd like to understand why python 3.11 is complaining about this (or if this is mypy or pre-commit...)
